find_package(PkgConfig)

# find gdalwrap (for gdal wrapper)
pkg_check_modules(PC_GDALWRAP REQUIRED gdalwrap)
set(GDALWRAP_DEFINITIONS ${PC_GDALWRAP_CFLAGS_OTHER})
find_path(GDALWRAP_INCLUDE_DIR gdalwrap/gdal.hpp
    HINTS ${PC_GDALWRAP_INCLUDEDIR} ${PC_GDALWRAP_INCLUDE_DIRS}
    PATH_SUFFIXES gdalwrap)
find_library(GDALWRAP_LIBRARY NAME gdalwrap
    HINTS ${PC_GDALWRAP_LIBDIR} ${PC_GDALWRAP_LIBRARY_DIRS} )
set(GDALWRAP_INCLUDE_DIRS ${GDALWRAP_INCLUDE_DIR})
set(GDALWRAP_LIBRARIES ${GDALWRAP_LIBRARY})
##

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GDALWRAP DEFAULT_MSG GDALWRAP_LIBRARY GDALWRAP_INCLUDE_DIR)
